source:
  type: kafka
  kafka:
    address:
      - 10.255.250.81:9092
    topic: train-data
    group: nbt-consumer-group3

sink:
  hostname: staging.bot.rnd.vcs.com
  secret: ""
  dataset_id: ""

logger:
  mode: development
